packages:
  # Include packages in the src directory
  - "apps/**"
  - "apps/bots/providers/**"
  - "packages/**"
  
  # Exclude build directories to prevent workspace conflicts
  - "!**/.next"
  - "!**/node_modules"
  - "!**/dist"
  - "!**/build"
